"""Build an ONNX model directly from a core graph.

Direct construction rather than a trip through ``torch.export``: it keeps
control of the opset and works without torch installed. The torch route is kept
only as a cross-check in the parity tests.

Weights are initialised here, not trained, so an exported model runs but has not
learned anything. Carrying trained weights arrives with phase 6.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from ntb.ir.core import CoreGraph, CoreNode
from ntb.ir.document import Document
from ntb.ir.types import DType, TensorType
from ntb.ops.registry import REGISTRY, OpRegistry
from ntb.ops.spec import OnnxMapping, OpSpec, ParamSpec
from ntb.shapes.infer import ShapeReport, infer_shapes
from ntb.spatial.resolve import resolve

if TYPE_CHECKING:  # pragma: no cover
    from onnx import ModelProto, NodeProto, TensorProto

BACKEND = "onnx"

#: Domain for ops NTB defines itself, which have no standard ONNX equivalent.
NTB_DOMAIN = "ntb.ops"

DEFAULT_OPSET = 20


class OnnxEmitError(Exception):
    """The graph cannot be exported to ONNX."""


def _require_onnx() -> Any:
    try:
        import onnx
    except ImportError as exc:  # pragma: no cover - exercised by the extras
        raise OnnxEmitError("ONNX export needs the onnx package: pip install 'ntb[onnx]'") from exc
    return onnx


_ELEMENT_TYPES = {
    DType.BOOL: "BOOL",
    DType.INT8: "INT8",
    DType.INT16: "INT16",
    DType.INT32: "INT32",
    DType.INT64: "INT64",
    DType.UINT8: "UINT8",
    DType.FLOAT16: "FLOAT16",
    DType.BFLOAT16: "BFLOAT16",
    DType.FLOAT32: "FLOAT",
    DType.FLOAT64: "DOUBLE",
    DType.COMPLEX64: "COMPLEX64",
}


def element_type(dtype: DType) -> int:
    """The ONNX ``TensorProto`` element type for an NTB dtype."""
    onnx = _require_onnx()
    name = _ELEMENT_TYPES.get(dtype)
    if name is None:  # pragma: no cover - the mapping is exhaustive
        raise OnnxEmitError(f"no ONNX element type for {dtype.value}")
    return int(getattr(onnx.TensorProto, name))


@dataclass(frozen=True, slots=True)
class ExportedModel:
    """An ONNX model and the opset it was built against."""

    model: ModelProto
    opset: int

    def save(self, path: Any) -> None:
        onnx = _require_onnx()
        onnx.save(self.model, str(path))


def export_document(
    document: Document, *, registry: OpRegistry = REGISTRY, opset: int = DEFAULT_OPSET
) -> ExportedModel:
    return export(resolve(document, registry=registry), registry=registry, opset=opset)


def export(
    graph: CoreGraph, *, registry: OpRegistry = REGISTRY, opset: int = DEFAULT_OPSET
) -> ExportedModel:
    """Build an ONNX model implementing ``graph``."""
    report = infer_shapes(graph, registry=registry)
    if report.issues:
        first = report.issues[0]
        raise OnnxEmitError(
            f"cannot export a graph that does not type-check: {first.node}: {first.message}"
        )
    return _Exporter(graph, report, registry, opset).build()


class _Exporter:
    def __init__(
        self, graph: CoreGraph, report: ShapeReport, registry: OpRegistry, opset: int
    ) -> None:
        self.onnx = _require_onnx()
        self.graph = graph
        self.report = report
        self.registry = registry
        self.opset = opset
        self.nodes: list[NodeProto] = []
        self.initialisers: list[TensorProto] = []
        self.uses_custom_domain = False
        self._names: dict[tuple[str, str], str] = {}

    def build(self) -> ExportedModel:
        for item in self.graph.inputs:
            self._names[(item.endpoint.node, item.endpoint.port)] = item.name

        for node in self.graph.topological_order():
            self._emit(node)

        graph = self.onnx.helper.make_graph(
            nodes=self.nodes,
            name=self.graph.name or "ntb",
            inputs=[self._value_info(item.name, item.type) for item in self.graph.inputs],
            outputs=[self._output_value_info(index) for index in range(len(self.graph.outputs))],
            initializer=self.initialisers,
        )
        opset_imports = [self.onnx.helper.make_opsetid("", self.opset)]
        if self.uses_custom_domain:
            opset_imports.append(self.onnx.helper.make_opsetid(NTB_DOMAIN, 1))

        model = self.onnx.helper.make_model(
            graph,
            opset_imports=opset_imports,
            producer_name="ntb",
            doc_string=f"Generated by NTB from {self.graph.name or 'an NTB document'}.",
        )
        self.onnx.checker.check_model(model)
        return ExportedModel(model=model, opset=self.opset)

    # -- nodes -------------------------------------------------------------

    def _emit(self, node: CoreNode) -> None:
        spec = self.registry.require(node.op)
        mapping = spec.onnx
        if mapping is None:
            raise OnnxEmitError(f"op {node.op!r} has no ONNX mapping")
        if mapping.since_opset > self.opset:
            raise OnnxEmitError(
                f"{node.op} needs opset {mapping.since_opset}, but this export targets "
                f"{self.opset}; pass --opset {mapping.since_opset}"
            )
        if mapping.custom:
            self.uses_custom_domain = True

        attrs = spec.resolved_attrs(node.attrs)
        slots: dict[str, str | list[str]] = {
            port.name: self._input_name(node, spec, port.name) for port in spec.inputs
        }
        for param in mapping.params:
            slots[param.name] = self._initialiser(node, param, attrs)

        order = mapping.input_order or (
            tuple(p.name for p in spec.inputs) + tuple(p.name for p in mapping.params)
        )
        inputs: list[str] = []
        for token in order:
            value = slots[token]
            # A variadic port occupies as many ONNX inputs as it has edges.
            if isinstance(value, list):
                inputs.extend(value)
            else:
                inputs.append(value)
        while inputs and not inputs[-1]:
            inputs.pop()  # ONNX reads a trailing "" as absent; drop it entirely.
        outputs = [self._declare(node.id, port.name) for port in spec.outputs]

        self.nodes.append(
            self.onnx.helper.make_node(
                mapping.op_type,
                inputs=inputs,
                outputs=outputs,
                name=node.id,
                domain=NTB_DOMAIN if mapping.custom else mapping.domain,
                **_attributes(mapping, attrs),
            )
        )

    def _input_name(self, node: CoreNode, spec: OpSpec, port: str) -> str | list[str]:
        declared = next(p for p in spec.inputs if p.name == port)
        arriving = [
            self._names[(edge.src.node, edge.src.port)]
            for edge in self.graph.incoming(node.id)
            if edge.dst.port == port
        ]
        if declared.variadic:
            if not arriving:
                raise OnnxEmitError(f"node {node.id!r} has nothing connected to {port!r}")
            return arriving
        if arriving:
            return arriving[0]
        pinned = self._names.get((node.id, port))
        if pinned is not None:
            return pinned
        if declared.optional:
            return ""
        raise OnnxEmitError(f"node {node.id!r} has nothing connected to {port!r}")

    def _initialiser(self, node: CoreNode, param: ParamSpec, attrs: dict[str, Any]) -> str:
        """Materialise a learned tensor as a graph initialiser.

        Values are freshly initialised, never trained: an exported model runs
        but has not learned anything until phase 6 carries weights across.
        """
        if param.when is not None and not attrs.get(param.when):
            return ""
        shape = resolve_param_shape(param, attrs)
        name = f"{node.id}_{param.name}".replace("/", "_")
        count = 1
        for size in shape:
            count *= size
        if param.ones:
            values = [1.0] * count
        elif param.zeros:
            values = [0.0] * count
        else:
            scale = (1.0 / max(count, 1)) ** 0.5
            values = [scale * (((i * 2654435761) % 2048) / 1024.0 - 1.0) for i in range(count)]
        self.initialisers.append(
            self.onnx.helper.make_tensor(
                name=name,
                data_type=element_type(DType.FLOAT32),
                dims=list(shape),
                vals=values,
            )
        )
        self._names[(node.id, param.name)] = name
        return name

    def _declare(self, node: str, port: str) -> str:
        name = f"{node}_{port}".replace("/", "_")
        self._names[(node, port)] = name
        return name

    # -- value info --------------------------------------------------------

    def _value_info(self, name: str, tensor: TensorType) -> Any:
        return self.onnx.helper.make_tensor_value_info(
            name, element_type(tensor.dtype), [_dimension(d) for d in tensor.shape]
        )

    def _output_value_info(self, index: int) -> Any:
        output = self.graph.outputs[index]
        endpoint = output.endpoint
        tensor = self.report.type_of(endpoint.node, endpoint.port)
        if tensor is None:  # pragma: no cover - guarded by the type check above
            raise OnnxEmitError(f"model output {endpoint} has no inferred type")
        return self._value_info(self._names[(endpoint.node, endpoint.port)], tensor)


def resolve_param_shape(param: ParamSpec, attrs: dict[str, Any]) -> tuple[int, ...]:
    """Evaluate a parameter shape against an op's attributes.

    Entries are integers, attribute expressions (``"in_channels // groups"``),
    or ``"*name"`` to splat a list attribute.
    """
    import sympy

    resolved: list[int] = []
    for entry in param.shape:
        if isinstance(entry, int):
            resolved.append(entry)
            continue
        if entry.startswith("*"):
            value = attrs.get(entry[1:])
            if not isinstance(value, (list, tuple)):
                raise OnnxEmitError(f"{entry} does not name a list attribute")
            resolved.extend(int(v) for v in value)
            continue
        try:
            expression = sympy.sympify(entry).subs(
                {k: v for k, v in attrs.items() if isinstance(v, int)}
            )
        except (sympy.SympifyError, TypeError) as exc:
            raise OnnxEmitError(f"cannot evaluate parameter shape {entry!r}: {exc}") from exc
        if not expression.is_Integer:
            raise OnnxEmitError(f"parameter shape {entry!r} did not resolve to an integer")
        resolved.append(int(expression))
    return tuple(resolved)


def _attributes(mapping: OnnxMapping, attrs: dict[str, Any]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for ntb_name, onnx_name in mapping.attr_map.items():
        value = attrs.get(ntb_name)
        if value is not None:
            result[onnx_name] = list(value) if isinstance(value, (list, tuple)) else value
    result.update(mapping.constants)
    return result


def _dimension(value: int | str) -> int | str:
    """ONNX takes an int for a fixed axis and a name for a dynamic one."""
    return value
