import torch
import torch.nn
import torch.nn.functional


class Cnn3d(torch.nn.Module):
    """Generated by NTB from cnn3d. Do not edit by hand."""

    def __init__(self) -> None:
        super().__init__()
        self.conv1 = torch.nn.Conv3d(
            in_channels=1,
            out_channels=16,
            kernel_size=(3, 3, 3),
            stride=(1, 1, 1),
            padding=(1, 1, 1),
            dilation=(1, 1, 1),
            groups=1,
            bias=True,
        )
        self.bn1 = torch.nn.BatchNorm3d(num_features=16, eps=1e-05, momentum=0.1, affine=True)
        self.pool1 = torch.nn.MaxPool3d(kernel_size=(2, 2, 2), stride=(2, 2, 2), padding=(0, 0, 0))
        self.conv2 = torch.nn.Conv3d(
            in_channels=16,
            out_channels=32,
            kernel_size=(3, 3, 3),
            stride=(1, 1, 1),
            padding=(1, 1, 1),
            dilation=(1, 1, 1),
            groups=1,
            bias=True,
        )
        self.bn2 = torch.nn.BatchNorm3d(num_features=32, eps=1e-05, momentum=0.1, affine=True)
        self.pool2 = torch.nn.MaxPool3d(kernel_size=(2, 2, 2), stride=(2, 2, 2), padding=(0, 0, 0))
        self.gap = torch.nn.AdaptiveAvgPool3d(output_size=1)
        self.head = torch.nn.Linear(in_features=32, out_features=10, bias=True)

    def forward(self, volume):
        conv1 = self.conv1(volume)
        bn1 = self.bn1(conv1)
        act1 = torch.nn.functional.relu(bn1)
        pool1 = self.pool1(act1)
        conv2 = self.conv2(pool1)
        bn2 = self.bn2(conv2)
        act2 = torch.nn.functional.relu(bn2)
        pool2 = self.pool2(act2)
        gap = self.gap(pool2)
        flat = torch.flatten(gap, start_dim=1, end_dim=-1)
        head = self.head(flat)
        return head
