import torch
import torch.nn
import torch.nn.functional


class Lattice3d(torch.nn.Module):
    """Generated by NTB from lattice-3d. Do not edit by hand."""

    def __init__(self) -> None:
        super().__init__()
        self.col0_0_fc = torch.nn.Linear(in_features=64, out_features=64, bias=True)
        self.col0_0_norm = torch.nn.LayerNorm(
            normalized_shape=(64,), eps=1e-05, elementwise_affine=True
        )
        self.col1_0_fc = torch.nn.Linear(in_features=64, out_features=64, bias=True)
        self.col2_0_fc = torch.nn.Linear(in_features=64, out_features=64, bias=True)
        self.col0_1_fc = torch.nn.Linear(in_features=64, out_features=64, bias=True)
        self.col1_0_norm = torch.nn.LayerNorm(
            normalized_shape=(64,), eps=1e-05, elementwise_affine=True
        )
        self.col2_0_norm = torch.nn.LayerNorm(
            normalized_shape=(64,), eps=1e-05, elementwise_affine=True
        )
        self.col0_1_norm = torch.nn.LayerNorm(
            normalized_shape=(64,), eps=1e-05, elementwise_affine=True
        )
        self.col3_0_fc = torch.nn.Linear(in_features=64, out_features=64, bias=True)
        self.col1_1_fc = torch.nn.Linear(in_features=64, out_features=64, bias=True)
        self.col2_1_fc = torch.nn.Linear(in_features=64, out_features=64, bias=True)
        self.col0_2_fc = torch.nn.Linear(in_features=64, out_features=64, bias=True)
        self.col3_0_norm = torch.nn.LayerNorm(
            normalized_shape=(64,), eps=1e-05, elementwise_affine=True
        )
        self.col1_1_norm = torch.nn.LayerNorm(
            normalized_shape=(64,), eps=1e-05, elementwise_affine=True
        )
        self.col2_1_norm = torch.nn.LayerNorm(
            normalized_shape=(64,), eps=1e-05, elementwise_affine=True
        )
        self.col0_2_norm = torch.nn.LayerNorm(
            normalized_shape=(64,), eps=1e-05, elementwise_affine=True
        )
        self.col3_1_fc = torch.nn.Linear(in_features=64, out_features=64, bias=True)
        self.col1_2_fc = torch.nn.Linear(in_features=64, out_features=64, bias=True)
        self.col2_2_fc = torch.nn.Linear(in_features=64, out_features=64, bias=True)
        self.col0_3_fc = torch.nn.Linear(in_features=64, out_features=64, bias=True)
        self.col3_1_norm = torch.nn.LayerNorm(
            normalized_shape=(64,), eps=1e-05, elementwise_affine=True
        )
        self.col1_2_norm = torch.nn.LayerNorm(
            normalized_shape=(64,), eps=1e-05, elementwise_affine=True
        )
        self.col2_2_norm = torch.nn.LayerNorm(
            normalized_shape=(64,), eps=1e-05, elementwise_affine=True
        )
        self.col0_3_norm = torch.nn.LayerNorm(
            normalized_shape=(64,), eps=1e-05, elementwise_affine=True
        )
        self.col3_2_fc = torch.nn.Linear(in_features=64, out_features=64, bias=True)
        self.col1_3_fc = torch.nn.Linear(in_features=64, out_features=64, bias=True)
        self.col2_3_fc = torch.nn.Linear(in_features=64, out_features=64, bias=True)
        self.col3_2_norm = torch.nn.LayerNorm(
            normalized_shape=(64,), eps=1e-05, elementwise_affine=True
        )
        self.col1_3_norm = torch.nn.LayerNorm(
            normalized_shape=(64,), eps=1e-05, elementwise_affine=True
        )
        self.col2_3_norm = torch.nn.LayerNorm(
            normalized_shape=(64,), eps=1e-05, elementwise_affine=True
        )
        self.col3_3_fc = torch.nn.Linear(in_features=64, out_features=64, bias=True)
        self.col3_3_norm = torch.nn.LayerNorm(
            normalized_shape=(64,), eps=1e-05, elementwise_affine=True
        )

    def forward(self, x):
        col0_0_mix = sum([x])
        col0_0_fc = self.col0_0_fc(col0_0_mix)
        col0_0_norm = self.col0_0_norm(col0_0_fc)
        col0_0_act = torch.nn.functional.gelu(col0_0_norm, approximate="none")
        col1_0_mix = sum([col0_0_act])
        col2_0_mix = sum([col0_0_act])
        col0_1_mix = sum([col0_0_act])
        col1_0_fc = self.col1_0_fc(col1_0_mix)
        col2_0_fc = self.col2_0_fc(col2_0_mix)
        col0_1_fc = self.col0_1_fc(col0_1_mix)
        col1_0_norm = self.col1_0_norm(col1_0_fc)
        col2_0_norm = self.col2_0_norm(col2_0_fc)
        col0_1_norm = self.col0_1_norm(col0_1_fc)
        col1_0_act = torch.nn.functional.gelu(col1_0_norm, approximate="none")
        col2_0_act = torch.nn.functional.gelu(col2_0_norm, approximate="none")
        col0_1_act = torch.nn.functional.gelu(col0_1_norm, approximate="none")
        col3_0_mix = sum([col1_0_act, col2_0_act])
        col1_1_mix = sum([col1_0_act, col0_1_act])
        col2_1_mix = sum([col2_0_act, col0_1_act])
        col0_2_mix = sum([col0_1_act])
        col3_0_fc = self.col3_0_fc(col3_0_mix)
        col1_1_fc = self.col1_1_fc(col1_1_mix)
        col2_1_fc = self.col2_1_fc(col2_1_mix)
        col0_2_fc = self.col0_2_fc(col0_2_mix)
        col3_0_norm = self.col3_0_norm(col3_0_fc)
        col1_1_norm = self.col1_1_norm(col1_1_fc)
        col2_1_norm = self.col2_1_norm(col2_1_fc)
        col0_2_norm = self.col0_2_norm(col0_2_fc)
        col3_0_act = torch.nn.functional.gelu(col3_0_norm, approximate="none")
        col1_1_act = torch.nn.functional.gelu(col1_1_norm, approximate="none")
        col2_1_act = torch.nn.functional.gelu(col2_1_norm, approximate="none")
        col0_2_act = torch.nn.functional.gelu(col0_2_norm, approximate="none")
        col3_1_mix = sum([col3_0_act, col1_1_act, col2_1_act])
        col1_2_mix = sum([col1_1_act, col0_2_act])
        col2_2_mix = sum([col2_1_act, col0_2_act])
        col0_3_mix = sum([col0_2_act])
        col3_1_fc = self.col3_1_fc(col3_1_mix)
        col1_2_fc = self.col1_2_fc(col1_2_mix)
        col2_2_fc = self.col2_2_fc(col2_2_mix)
        col0_3_fc = self.col0_3_fc(col0_3_mix)
        col3_1_norm = self.col3_1_norm(col3_1_fc)
        col1_2_norm = self.col1_2_norm(col1_2_fc)
        col2_2_norm = self.col2_2_norm(col2_2_fc)
        col0_3_norm = self.col0_3_norm(col0_3_fc)
        col3_1_act = torch.nn.functional.gelu(col3_1_norm, approximate="none")
        col1_2_act = torch.nn.functional.gelu(col1_2_norm, approximate="none")
        col2_2_act = torch.nn.functional.gelu(col2_2_norm, approximate="none")
        col0_3_act = torch.nn.functional.gelu(col0_3_norm, approximate="none")
        col3_2_mix = sum([col3_1_act, col1_2_act, col2_2_act])
        col1_3_mix = sum([col1_2_act, col0_3_act])
        col2_3_mix = sum([col2_2_act, col0_3_act])
        col3_2_fc = self.col3_2_fc(col3_2_mix)
        col1_3_fc = self.col1_3_fc(col1_3_mix)
        col2_3_fc = self.col2_3_fc(col2_3_mix)
        col3_2_norm = self.col3_2_norm(col3_2_fc)
        col1_3_norm = self.col1_3_norm(col1_3_fc)
        col2_3_norm = self.col2_3_norm(col2_3_fc)
        col3_2_act = torch.nn.functional.gelu(col3_2_norm, approximate="none")
        col1_3_act = torch.nn.functional.gelu(col1_3_norm, approximate="none")
        col2_3_act = torch.nn.functional.gelu(col2_3_norm, approximate="none")
        col3_3_mix = sum([col3_2_act, col1_3_act, col2_3_act])
        col3_3_fc = self.col3_3_fc(col3_3_mix)
        col3_3_norm = self.col3_3_norm(col3_3_fc)
        col3_3_act = torch.nn.functional.gelu(col3_3_norm, approximate="none")
        return col3_3_act
