import torch
import torch.nn
import torch.nn.functional


class Mlp(torch.nn.Module):
    """Generated by NTB from mlp. Do not edit by hand."""

    def __init__(self) -> None:
        super().__init__()
        self.fc1 = torch.nn.Linear(in_features=784, out_features=128, bias=True)
        self.fc2 = torch.nn.Linear(in_features=128, out_features=10, bias=True)

    def forward(self, x):
        fc1 = self.fc1(x)
        act1 = torch.nn.functional.relu(fc1)
        fc2 = self.fc2(act1)
        return fc2
