import torch
import torch.nn
import torch.nn.functional


class TransformerEncoderBlock(torch.nn.Module):
    """Generated by NTB from transformer-encoder-block. Do not edit by hand."""

    def __init__(self) -> None:
        super().__init__()
        self.norm1 = torch.nn.LayerNorm(normalized_shape=(512,), eps=1e-05, elementwise_affine=True)
        self.attn = torch.nn.MultiheadAttention(
            embed_dim=512, num_heads=8, dropout=0.0, bias=True, batch_first=True
        )
        self.drop1 = torch.nn.Dropout(p=0.1)
        self.norm2 = torch.nn.LayerNorm(normalized_shape=(512,), eps=1e-05, elementwise_affine=True)
        self.ff_in = torch.nn.Linear(in_features=512, out_features=2048, bias=True)
        self.ff_out = torch.nn.Linear(in_features=2048, out_features=512, bias=True)
        self.drop2 = torch.nn.Dropout(p=0.1)

    def forward(self, x):
        norm1 = self.norm1(x)
        attn_out, _ = self.attn(norm1, norm1, norm1)
        drop1 = self.drop1(attn_out)
        res1 = torch.add(drop1, norm1)
        norm2 = self.norm2(res1)
        ff_in = self.ff_in(norm2)
        act = torch.nn.functional.gelu(ff_in, approximate="tanh")
        ff_out = self.ff_out(act)
        drop2 = self.drop2(ff_out)
        res2 = torch.add(drop2, res1)
        return res2
