import torch
import torch.nn
import torch.nn.functional


class VerticalTower(torch.nn.Module):
    """Generated by NTB from vertical-tower. Do not edit by hand."""

    def __init__(self) -> None:
        super().__init__()
        self.stack_0_fc = torch.nn.Linear(in_features=256, out_features=256, bias=True)
        self.stack_1_fc = torch.nn.Linear(in_features=256, out_features=256, bias=True)
        self.stack_2_fc = torch.nn.Linear(in_features=256, out_features=256, bias=True)
        self.stack_3_fc = torch.nn.Linear(in_features=256, out_features=256, bias=True)
        self.stack_4_fc = torch.nn.Linear(in_features=256, out_features=256, bias=True)
        self.stack_5_fc = torch.nn.Linear(in_features=256, out_features=256, bias=True)
        self.stack_6_fc = torch.nn.Linear(in_features=256, out_features=256, bias=True)
        self.stack_7_fc = torch.nn.Linear(in_features=256, out_features=256, bias=True)
        self.stack_8_fc = torch.nn.Linear(in_features=256, out_features=256, bias=True)
        self.stack_9_fc = torch.nn.Linear(in_features=256, out_features=256, bias=True)
        self.stack_10_fc = torch.nn.Linear(in_features=256, out_features=256, bias=True)
        self.stack_11_fc = torch.nn.Linear(in_features=256, out_features=256, bias=True)

    def forward(self, x):
        stack_0_fc = self.stack_0_fc(x)
        stack_0_act = torch.nn.functional.relu(stack_0_fc)
        stack_1_fc = self.stack_1_fc(stack_0_act)
        stack_1_act = torch.nn.functional.relu(stack_1_fc)
        stack_2_fc = self.stack_2_fc(stack_1_act)
        stack_2_act = torch.nn.functional.relu(stack_2_fc)
        stack_3_fc = self.stack_3_fc(stack_2_act)
        stack_3_act = torch.nn.functional.relu(stack_3_fc)
        stack_4_fc = self.stack_4_fc(stack_3_act)
        stack_4_act = torch.nn.functional.relu(stack_4_fc)
        stack_5_fc = self.stack_5_fc(stack_4_act)
        stack_5_act = torch.nn.functional.relu(stack_5_fc)
        stack_6_fc = self.stack_6_fc(stack_5_act)
        stack_6_act = torch.nn.functional.relu(stack_6_fc)
        stack_7_fc = self.stack_7_fc(stack_6_act)
        stack_7_act = torch.nn.functional.relu(stack_7_fc)
        stack_8_fc = self.stack_8_fc(stack_7_act)
        stack_8_act = torch.nn.functional.relu(stack_8_fc)
        stack_9_fc = self.stack_9_fc(stack_8_act)
        stack_9_act = torch.nn.functional.relu(stack_9_fc)
        stack_10_fc = self.stack_10_fc(stack_9_act)
        stack_10_act = torch.nn.functional.relu(stack_10_fc)
        stack_11_fc = self.stack_11_fc(stack_10_act)
        stack_11_act = torch.nn.functional.relu(stack_11_fc)
        return stack_11_act
