import keras


def build_cnn3d() -> keras.Model:
    """Generated by NTB from cnn3d. Do not edit by hand."""
    volume = keras.Input(batch_shape=(None, 1, 32, 64, 64), dtype="float32", name="volume")
    conv1_pad = keras.layers.ZeroPadding3D(
        padding=((1, 1), (1, 1), (1, 1)), data_format="channels_first"
    )(volume)
    conv1 = keras.layers.Conv3D(
        filters=16,
        kernel_size=(3, 3, 3),
        strides=(1, 1, 1),
        dilation_rate=(1, 1, 1),
        groups=1,
        use_bias=True,
        data_format="channels_first",
        padding="valid",
    )(conv1_pad)
    bn1 = keras.layers.BatchNormalization(epsilon=1e-05, momentum=0.1, scale=True, axis=1)(conv1)
    act1 = keras.activations.relu(bn1)
    pool1 = keras.layers.MaxPooling3D(
        pool_size=(2, 2, 2), strides=(2, 2, 2), data_format="channels_first", padding="valid"
    )(act1)
    conv2_pad = keras.layers.ZeroPadding3D(
        padding=((1, 1), (1, 1), (1, 1)), data_format="channels_first"
    )(pool1)
    conv2 = keras.layers.Conv3D(
        filters=32,
        kernel_size=(3, 3, 3),
        strides=(1, 1, 1),
        dilation_rate=(1, 1, 1),
        groups=1,
        use_bias=True,
        data_format="channels_first",
        padding="valid",
    )(conv2_pad)
    bn2 = keras.layers.BatchNormalization(epsilon=1e-05, momentum=0.1, scale=True, axis=1)(conv2)
    act2 = keras.activations.relu(bn2)
    pool2 = keras.layers.MaxPooling3D(
        pool_size=(2, 2, 2), strides=(2, 2, 2), data_format="channels_first", padding="valid"
    )(act2)
    gap = keras.layers.GlobalAveragePooling3D(data_format="channels_first", keepdims=True)(pool2)
    flat = keras.ops.reshape(gap, newshape=(-1, 32))
    head = keras.layers.Dense(units=10, use_bias=True)(flat)
    return keras.Model(inputs=volume, outputs=head, name="cnn3d")
