import keras


def build_mlp() -> keras.Model:
    """Generated by NTB from mlp. Do not edit by hand."""
    x = keras.Input(batch_shape=(None, 784), dtype="float32", name="x")
    fc1 = keras.layers.Dense(units=128, use_bias=True)(x)
    act1 = keras.activations.relu(fc1)
    fc2 = keras.layers.Dense(units=10, use_bias=True)(act1)
    return keras.Model(inputs=x, outputs=fc2, name="mlp")
