import keras


def build_transformer_encoder_block() -> keras.Model:
    """Generated by NTB from transformer-encoder-block. Do not edit by hand."""
    x = keras.Input(batch_shape=(None, None, 512), dtype="float32", name="x")
    norm1 = keras.layers.LayerNormalization(epsilon=1e-05, scale=True)(x)
    attn_out, _ = keras.layers.MultiHeadAttention(
        num_heads=8, dropout=0.0, use_bias=True, key_dim=64
    )(norm1, norm1, norm1, return_attention_scores=True)
    drop1 = keras.layers.Dropout(rate=0.1)(attn_out)
    res1 = keras.ops.add(drop1, norm1)
    norm2 = keras.layers.LayerNormalization(epsilon=1e-05, scale=True)(res1)
    ff_in = keras.layers.Dense(units=2048, use_bias=True)(norm2)
    act = keras.activations.gelu(ff_in)
    ff_out = keras.layers.Dense(units=512, use_bias=True)(act)
    drop2 = keras.layers.Dropout(rate=0.1)(ff_out)
    res2 = keras.ops.add(drop2, res1)
    return keras.Model(inputs=x, outputs=res2, name="transformer_encoder_block")
