// Generates src/ir.gen.ts from the checked-in JSON Schema.
//
// The schema is itself generated from the pydantic models, so this is the last
// link of one chain: pydantic -> JSON Schema -> TypeScript. Hand-writing the
// TypeScript would put a second definition of the IR in the repo.
//
//   node scripts/gen-types.mjs           rewrite the file
//   node scripts/gen-types.mjs --check   fail if it is stale (CI)

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const schemaPath = resolve(here, "../../../schema/ntb-ir-v1.json");
const target = resolve(here, "../src/ir.gen.ts");

const schema = JSON.parse(readFileSync(schemaPath, "utf8"));

// pydantic titles every field, and the generator turns each title into its own
// exported alias ("Doc1", "Id2", a `Node` that is really a string). Drop the
// per-property titles; the $defs keep theirs, which is where the names matter.
//
// `prefixItems` (a fixed-length tuple, which is how pos and extent are declared)
// is 2020-12 syntax the generator does not read, and it emits `unknown` for it.
function normalise(node) {
  if (Array.isArray(node)) return node.forEach(normalise);
  if (!node || typeof node !== "object") return;
  if (node.prefixItems) {
    node.items = node.prefixItems;
    delete node.prefixItems;
  }
  for (const [key, value] of Object.entries(node)) {
    if (key === "properties" && value && typeof value === "object") {
      for (const property of Object.values(value)) {
        if (property && typeof property === "object") delete property.title;
      }
    }
    normalise(value);
  }
}
normalise(schema);
const banner = "// Generated by scripts/gen-types.mjs from schema/ntb-ir-v1.json. Do not edit.";

const body = await compile(schema, "Document", {
  bannerComment: banner,
  additionalProperties: false,
  style: { printWidth: 100 },
});

const current = (() => {
  try {
    return readFileSync(target, "utf8");
  } catch {
    return null;
  }
})();

if (process.argv.includes("--check")) {
  if (current !== body) {
    console.error("src/ir.gen.ts is stale; run `npm run types`");
    process.exit(1);
  }
  console.log("src/ir.gen.ts is up to date");
} else if (current !== body) {
  writeFileSync(target, body);
  console.log("wrote src/ir.gen.ts");
} else {
  console.log("src/ir.gen.ts is up to date");
}
