// Generated by scripts/gen-types.mjs from schema/ntb-ir-v1.json. Do not edit.

/**
 * A world axis. ``Z`` is the vertical stacking axis by convention.
 */
export type Axis = "x" | "y" | "z";
export type PortDirection = "in" | "out";
/**
 * Element types. Closed set: each must exist in torch, Keras 3 and ONNX.
 */
export type DType =
  | "bool"
  | "int8"
  | "int16"
  | "int32"
  | "int64"
  | "uint8"
  | "float16"
  | "bfloat16"
  | "float32"
  | "float64"
  | "complex64";
/**
 * Which way a block faces, i.e. along which axis it consumes and produces.
 */
export type Orientation = "along_x" | "along_y" | "along_z";
/**
 * A world axis. ``Z`` is the vertical stacking axis by convention.
 */
export type Axis1 = "x" | "y" | "z";
/**
 * The closed set of ways geometry may generate connectivity.
 */
export type SpatialRuleKind = "vertical_stack" | "axis_projection" | "neighborhood" | "lattice";

/**
 * A complete `.ntb` file.
 *
 * Structural validation only; semantic validation lives in :mod:`ntb.validate`.
 */
export interface Document {
  doc?: string;
  metadata?: {
    [k: string]: unknown;
  };
  modules?: Module[];
  name?: string;
  ntb_version?: string;
  /**
   * Id of the module that is the model itself.
   */
  root?: string;
  schema_version?: number;
}
/**
 * A reusable, parameterisable subgraph.
 *
 * Layers, transformer blocks and whole models are all Modules; NTB hardcodes
 * no notion of "a layer".
 */
export interface Module {
  doc?: string;
  edges?: Edge[];
  generators?: Generator[];
  id: string;
  inputs?: Port[];
  name?: string;
  nodes?: Node[];
  outputs?: Port[];
  /**
   * Module-level parameters referenceable from node attributes.
   */
  params?: {
    [k: string]: unknown;
  };
  spatial_rules?: SpatialRule[];
}
/**
 * An authored connection. Rule-derived edges appear only in the core IR.
 */
export interface Edge {
  dst: Endpoint;
  id: string;
  src: Endpoint;
}
/**
 * One end of an edge: a port on a node.
 */
export interface Endpoint {
  node: string;
  port?: string;
}
/**
 * Repeats a module along an axis, parameterising it by the 0-based index ``i``.
 *
 * Keeps "N stacked layers" a single object rather than N copied nodes.
 */
export interface Generator {
  /**
   * Attribute name -> expression in the loop variable `i`.
   */
  attr_bindings?: {
    [k: string]: string;
  };
  axis?: Axis;
  /**
   * Wire instance i into i+1. False lays them out in parallel.
   */
  chain?: boolean;
  count: number;
  id: string;
  label?: string;
  /**
   * Id of the Module to instantiate.
   */
  module?: string;
  /**
   * @minItems 3
   * @maxItems 3
   */
  origin?: [number, number, number];
  /**
   * Spacing between consecutive instances along `axis`.
   */
  step?: number;
}
/**
 * A named connection point. Ops declare ports; nodes only carry pinned ones.
 */
export interface Port {
  direction: PortDirection;
  name: string;
  optional?: boolean;
  /**
   * Author-pinned type. None means 'infer me'.
   */
  type?: TensorType | null;
}
/**
 * The static type of a value flowing along an edge.
 */
export interface TensorType {
  dtype?: DType;
  /**
   * Informational hint ('NCHW'); the op registry defines the truth.
   */
  layout?: string | null;
  shape?: (number | string)[];
}
/**
 * One operation, or one instance of a module, placed in space.
 */
export interface Node {
  /**
   * Op attributes, validated against the op's attribute schema.
   */
  attrs?: {
    [k: string]: unknown;
  };
  id: string;
  /**
   * Human label; free text, may be empty.
   */
  name?: string;
  /**
   * Registry op name, or 'ntb.module' to instantiate a Module.
   */
  op: string;
  placement?: Placement;
  ports?: Port[];
}
/**
 * Where a node sits. ``pos`` is the block centre, ``extent`` its size.
 */
export interface Placement {
  /**
   * @minItems 3
   * @maxItems 3
   */
  extent?: [number, number, number];
  orient?: Orientation;
  /**
   * @minItems 3
   * @maxItems 3
   */
  pos?: [number, number, number];
}
/**
 * Derives edges from where its ``members`` sit. Never invents nodes.
 *
 * Resolution is deterministic: same placements, same edges, same order.
 */
export interface SpatialRule {
  axis?: Axis1;
  /**
   * NEIGHBORHOOD and LATTICE only; the ordered kinds would cycle.
   */
  bidirectional?: boolean;
  id: string;
  /**
   * Port on the target node that generated edges arrive at.
   */
  input_port?: string;
  kind: SpatialRuleKind;
  label?: string;
  /**
   * Ids of the nodes this rule wires, within the owning module.
   */
  members: string[];
  /**
   * Port on the source node that generated edges leave from.
   */
  output_port?: string;
  /**
   * Euclidean radius for NEIGHBORHOOD; ignored by other kinds.
   */
  radius?: number | null;
}
